(
    schema_version: 1,
    name: "Aimant + plaque de fer",
    depth: 0.01,
    size: 0.4,
    ambient: 20.0,
    objects: [
        (
            id: 1,
            name: "Aimant 1",
            shape: Rect(
                w: 0.02,
                h: 0.04,
            ),
            pos: (-0.025, 0.0, 0.0),
            angle: 0.0,
            material: "NdFeB N42",
            mag_angle: 0.0,
            turns: 0.0,
            current: 0.0,
            temperature: 20.0,
        ),
        (
            id: 2,
            name: "Plaque 2",
            shape: Rect(
                w: 0.016,
                h: 0.06,
            ),
            pos: (0.02, 0.0, 0.0),
            angle: 0.0,
            material: "Fer pur (Armco)",
            mag_angle: 0.0,
            turns: 0.0,
            current: 0.0,
            temperature: 20.0,
        ),
    ],
    materials: [
        (
            name: "NdFeB N35",
            class: Magnet,
            mu_r: 1.05,
            chi: 0.0,
            br: 1.19,
            alpha_br: -0.12,
            t_curie: 310.0,
            t_critical: 0.0,
            density: 7500.0,
        ),
        (
            name: "NdFeB N42",
            class: Magnet,
            mu_r: 1.05,
            chi: 0.0,
            br: 1.3,
            alpha_br: -0.12,
            t_curie: 310.0,
            t_critical: 0.0,
            density: 7500.0,
        ),
        (
            name: "NdFeB N52",
            class: Magnet,
            mu_r: 1.05,
            chi: 0.0,
            br: 1.45,
            alpha_br: -0.12,
            t_curie: 310.0,
            t_critical: 0.0,
            density: 7500.0,
        ),
        (
            name: "NdFeB N42SH",
            class: Magnet,
            mu_r: 1.05,
            chi: 0.0,
            br: 1.3,
            alpha_br: -0.12,
            t_curie: 340.0,
            t_critical: 0.0,
            density: 7500.0,
        ),
        (
            name: "SmCo 2:17",
            class: Magnet,
            mu_r: 1.05,
            chi: 0.0,
            br: 1.07,
            alpha_br: -0.035,
            t_curie: 800.0,
            t_critical: 0.0,
            density: 8400.0,
        ),
        (
            name: "Ferrite Sr (Y30)",
            class: Magnet,
            mu_r: 1.1,
            chi: 0.0,
            br: 0.385,
            alpha_br: -0.2,
            t_curie: 450.0,
            t_critical: 0.0,
            density: 4900.0,
        ),
        (
            name: "AlNiCo 5",
            class: Magnet,
            mu_r: 3.5,
            chi: 0.0,
            br: 1.26,
            alpha_br: -0.02,
            t_curie: 860.0,
            t_critical: 0.0,
            density: 7300.0,
        ),
        (
            name: "Fer pur (Armco)",
            class: Ferro,
            mu_r: 5000.0,
            chi: 0.0,
            br: 0.0,
            alpha_br: 0.0,
            t_curie: 770.0,
            t_critical: 0.0,
            density: 7870.0,
        ),
        (
            name: "Acier doux (S235)",
            class: Ferro,
            mu_r: 1500.0,
            chi: 0.0,
            br: 0.0,
            alpha_br: 0.0,
            t_curie: 770.0,
            t_critical: 0.0,
            density: 7850.0,
        ),
        (
            name: "Acier électrique Fe-3%Si",
            class: Ferro,
            mu_r: 7000.0,
            chi: 0.0,
            br: 0.0,
            alpha_br: 0.0,
            t_curie: 740.0,
            t_critical: 0.0,
            density: 7650.0,
        ),
        (
            name: "Mu-métal",
            class: Ferro,
            mu_r: 80000.0,
            chi: 0.0,
            br: 0.0,
            alpha_br: 0.0,
            t_curie: 400.0,
            t_critical: 0.0,
            density: 8700.0,
        ),
        (
            name: "Permalloy 50% Ni",
            class: Ferro,
            mu_r: 50000.0,
            chi: 0.0,
            br: 0.0,
            alpha_br: 0.0,
            t_curie: 480.0,
            t_critical: 0.0,
            density: 8200.0,
        ),
        (
            name: "Fer-cobalt (Permendur)",
            class: Ferro,
            mu_r: 10000.0,
            chi: 0.0,
            br: 0.0,
            alpha_br: 0.0,
            t_curie: 940.0,
            t_critical: 0.0,
            density: 8100.0,
        ),
        (
            name: "Ferrite douce MnZn",
            class: Ferro,
            mu_r: 5000.0,
            chi: 0.0,
            br: 0.0,
            alpha_br: 0.0,
            t_curie: 200.0,
            t_critical: 0.0,
            density: 4800.0,
        ),
        (
            name: "Nickel",
            class: Ferro,
            mu_r: 300.0,
            chi: 0.0,
            br: 0.0,
            alpha_br: 0.0,
            t_curie: 354.0,
            t_critical: 0.0,
            density: 8900.0,
        ),
        (
            name: "Cobalt",
            class: Ferro,
            mu_r: 150.0,
            chi: 0.0,
            br: 0.0,
            alpha_br: 0.0,
            t_curie: 1115.0,
            t_critical: 0.0,
            density: 8900.0,
        ),
        (
            name: "Gadolinium",
            class: Ferro,
            mu_r: 50.0,
            chi: 0.0,
            br: 0.0,
            alpha_br: 0.0,
            t_curie: 20.0,
            t_critical: 0.0,
            density: 7900.0,
        ),
        (
            name: "Aluminium",
            class: Para,
            mu_r: 1.000022,
            chi: 0.000022,
            br: 0.0,
            alpha_br: 0.0,
            t_curie: 0.0,
            t_critical: 0.0,
            density: 2700.0,
        ),
        (
            name: "Platine",
            class: Para,
            mu_r: 1.00027,
            chi: 0.00027,
            br: 0.0,
            alpha_br: 0.0,
            t_curie: 0.0,
            t_critical: 0.0,
            density: 21450.0,
        ),
        (
            name: "Titane",
            class: Para,
            mu_r: 1.00018,
            chi: 0.00018,
            br: 0.0,
            alpha_br: 0.0,
            t_curie: 0.0,
            t_critical: 0.0,
            density: 4510.0,
        ),
        (
            name: "Tungstène",
            class: Para,
            mu_r: 1.000078,
            chi: 0.000078,
            br: 0.0,
            alpha_br: 0.0,
            t_curie: 0.0,
            t_critical: 0.0,
            density: 19300.0,
        ),
        (
            name: "Graphite pyrolytique",
            class: Dia,
            mu_r: 0.99955,
            chi: -0.00045,
            br: 0.0,
            alpha_br: 0.0,
            t_curie: 0.0,
            t_critical: 0.0,
            density: 2200.0,
        ),
        (
            name: "Bismuth",
            class: Dia,
            mu_r: 0.999834,
            chi: -0.000166,
            br: 0.0,
            alpha_br: 0.0,
            t_curie: 0.0,
            t_critical: 0.0,
            density: 9780.0,
        ),
        (
            name: "Eau",
            class: Dia,
            mu_r: 0.999991,
            chi: -0.000009,
            br: 0.0,
            alpha_br: 0.0,
            t_curie: 0.0,
            t_critical: 0.0,
            density: 1000.0,
        ),
        (
            name: "Diamant",
            class: Dia,
            mu_r: 0.999978,
            chi: -0.000022,
            br: 0.0,
            alpha_br: 0.0,
            t_curie: 0.0,
            t_critical: 0.0,
            density: 3510.0,
        ),
        (
            name: "Argent",
            class: Dia,
            mu_r: 0.999976,
            chi: -0.000024,
            br: 0.0,
            alpha_br: 0.0,
            t_curie: 0.0,
            t_critical: 0.0,
            density: 10500.0,
        ),
        (
            name: "Or",
            class: Dia,
            mu_r: 0.999966,
            chi: -0.000034,
            br: 0.0,
            alpha_br: 0.0,
            t_curie: 0.0,
            t_critical: 0.0,
            density: 19300.0,
        ),
        (
            name: "Cuivre (bobinage)",
            class: Conductor,
            mu_r: 0.9999904,
            chi: -0.0000096,
            br: 0.0,
            alpha_br: 0.0,
            t_curie: 0.0,
            t_critical: 0.0,
            density: 8960.0,
        ),
        (
            name: "YBCO",
            class: Superconductor,
            mu_r: 0.0001,
            chi: -1.0,
            br: 0.0,
            alpha_br: 0.0,
            t_curie: 0.0,
            t_critical: -181.14999999999998,
            density: 6300.0,
        ),
        (
            name: "BSCCO-2223",
            class: Superconductor,
            mu_r: 0.0001,
            chi: -1.0,
            br: 0.0,
            alpha_br: 0.0,
            t_curie: 0.0,
            t_critical: -163.14999999999998,
            density: 6500.0,
        ),
        (
            name: "MgB2",
            class: Superconductor,
            mu_r: 0.0001,
            chi: -1.0,
            br: 0.0,
            alpha_br: 0.0,
            t_curie: 0.0,
            t_critical: -234.14999999999998,
            density: 2570.0,
        ),
        (
            name: "Niobium",
            class: Superconductor,
            mu_r: 0.0001,
            chi: -1.0,
            br: 0.0,
            alpha_br: 0.0,
            t_curie: 0.0,
            t_critical: -263.9,
            density: 8570.0,
        ),
        (
            name: "Plomb",
            class: Superconductor,
            mu_r: 0.0001,
            chi: -1.0,
            br: 0.0,
            alpha_br: 0.0,
            t_curie: 0.0,
            t_critical: -265.95,
            density: 11340.0,
        ),
    ],
    probes: [],
    cut_line: None,
    next_id: 3,
)